import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

export const getStyles = (screenOrientation, clockDateSize, isLightMode = false) => {
  const { width } = Dimensions.get('window');
  const primaryTextColor = isLightMode ? '#000000' : '#FFFFFF';
  const buttonBgColor = isLightMode ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.15)';
  const buttonBorderColor = isLightMode ? 'rgba(0,0,0,0.15)' : 'rgba(255,255,255,0.2)';

  return StyleSheet.create({
    container: {
      flex: 1,
      minHeight: '100%',
      minWidth: '100%',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: screenOrientation === 'landscape' ? 40 : 20,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + 10 : 20,
      paddingBottom: 10,
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      color: primaryTextColor,
      letterSpacing: 0.5,
      textShadowColor: isLightMode ? 'rgba(255, 255, 255, 0.5)' : 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    },
    headerButtons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerButton: {
      marginLeft: 15,
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: buttonBgColor,
      borderWidth: 1,
      borderColor: buttonBorderColor,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    selectAllButton: {
      marginRight: 10,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: buttonBgColor,
      borderWidth: 1,
      borderColor: buttonBorderColor,
      paddingHorizontal: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    selectAllText: {
      color: primaryTextColor,
      fontSize: 14,
      fontWeight: 'bold',
    },
    controlPanel: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 10,
      marginBottom: 5,
    },
    selectionText: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: 14,
      fontWeight: '600',
    },
    // FAB Style for Start Button
    fabButton: {
      position: 'absolute',
      bottom: 80,
      alignSelf: 'center',
      backgroundColor: '#E94560', // Default accent, will be overridden by gradients if needed
      paddingHorizontal: 30,
      paddingVertical: 16,
      borderRadius: 30,
      flexDirection: 'row',
      alignItems: 'center',
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      zIndex: 100,
    },
    disabledFab: {
      backgroundColor: '#666',
      opacity: 0.7,
    },
    fabText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    photoGrid: {
      flex: 1,
      paddingHorizontal: 15,
    },
    photoItem: {
      flex: 1/3,
      aspectRatio: 1,
      margin: 6,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: 'rgba(255,255,255,0.05)',
    },
    selectedPhoto: {
      // Border is now handled by the overlay or a ring view
      transform: [{ scale: 0.95 }],
    },
    photoThumbnail: {
      width: '100%',
      height: '100%',
      borderRadius: 12,
    },
    selectedOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.4)',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 12,
      borderWidth: 3,
      borderColor: '#4CD964', // Green accent for selection
    },
    selectedText: {
      color: '#fff',
      fontSize: 24,
      fontWeight: 'bold',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    // Modernized Styles
    loadingFooter: {
      paddingVertical: 20,
      alignItems: 'center',
    },
    loadingText: {
      color: '#fff',
      marginTop: 10,
      fontSize: 16,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 100,
    },
    emptyText: {
      color: 'rgba(255,255,255,0.7)',
      fontSize: 18,
      marginTop: 20,
      fontWeight: '500',
    },
    permissionContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 40,
    },
    permissionTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: primaryTextColor,
      textAlign: 'center',
      marginBottom: 20,
    },
    permissionMessage: {
      fontSize: 16,
      color: isLightMode ? 'rgba(0,0,0,0.8)' : 'rgba(255,255,255,0.8)',
      textAlign: 'center',
      marginBottom: 30,
      lineHeight: 24,
    },
    retryButton: {
      backgroundColor: '#007AFF',
      paddingHorizontal: 30,
      paddingVertical: 15,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 4,
    },
    retryButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    // 設定画面のスタイル
    settingsContainer: {
      flex: 1,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      overflow: 'hidden',
    },
    settingsContent: {
      flex: 1,
    },
    settingsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: screenOrientation === 'landscape' ? 40 : 20,
      paddingVertical: screenOrientation === 'landscape' ? 15 : 20,
      borderBottomWidth: 1,
      borderBottomColor: isLightMode ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)',
      backgroundColor: isLightMode ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.2)',
    },
    settingsTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: primaryTextColor,
    },
    closeButton: {
      padding: 8,
    },
    settingsScroll: {
      flex: 1,
      paddingHorizontal: screenOrientation === 'landscape' ? 40 : 20,
      paddingVertical: 20,
    },
    settingSection: {
      marginBottom: 30,
      backgroundColor: isLightMode ? 'rgba(0,0,0,0.05)' : 'rgba(255,255,255,0.05)',
      borderRadius: 16,
      padding: 20,
    },
    settingLabel: {
      fontSize: 18,
      fontWeight: '600',
      color: primaryTextColor,
      marginBottom: 15,
      flexDirection: 'row',
      alignItems: 'center',
    },
    languageButtons: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    languageButton: {
      backgroundColor: isLightMode ? 'rgba(0,0,0,0.05)' : 'rgba(255,255,255,0.1)',
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: isLightMode ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)',
    },
    activeLanguageButton: {
      backgroundColor: '#007AFF',
      borderColor: '#007AFF',
    },
    languageButtonText: {
      color: isLightMode ? 'rgba(0,0,0,0.7)' : 'rgba(255,255,255,0.8)',
      fontWeight: '600',
      fontSize: 15,
    },
    activeLanguageButtonText: {
      color: '#fff',
      fontWeight: '700',
    },
    colorGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    colorButton: {
      width: 60,
      height: 60,
      borderRadius: 15,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: isLightMode ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)',
    },
    activeColorButton: {
      borderColor: primaryTextColor,
      borderWidth: 3,
      transform: [{ scale: 1.1 }],
    },
    colorButtonText: {
      fontSize: 10,
      fontWeight: '600',
      color: isLightMode ? 'rgba(0,0,0,0.7)' : 'rgba(255,255,255,0.8)',
      marginTop: 4,
      textShadowColor: isLightMode ? 'rgba(255,255,255,0.5)' : 'rgba(0,0,0,0.5)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    intervalButtons: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    intervalButton: {
      backgroundColor: isLightMode ? 'rgba(0,0,0,0.05)' : 'rgba(255,255,255,0.1)',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: isLightMode ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)',
    },
    activeIntervalButton: {
      backgroundColor: '#007AFF',
      borderColor: '#007AFF',
    },
    intervalButtonText: {
      color: isLightMode ? 'rgba(0,0,0,0.7)' : 'rgba(255,255,255,0.8)',
      fontWeight: '600',
      fontSize: 15,
    },
    activeIntervalButtonText: {
      color: '#fff',
      fontWeight: '700',
    },
    // スライドショー画面のスタイル
    slideshowContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#000',
    },
    slideshowTouchArea: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    slideshowCloseButton: {
      position: 'absolute',
      top: screenOrientation === 'landscape' ? 30 : 50,
      right: screenOrientation === 'landscape' ? 40 : 20,
      zIndex: 10,
      justifyContent: 'center',
      alignItems: 'center',
      opacity: 0.8,
    },
    slideshowCloseText: {
      color: '#fff',
      fontSize: 40,
      fontWeight: 'bold',
    },
    slideshowImage: {
      width: '100%',
      height: '100%',
    },
    slideshowImagePortrait: {
      maxWidth: '100%',
      maxHeight: '100%',
    },
    slideshowImageLandscape: {
      maxWidth: '100%',
      maxHeight: '100%',
    },
    slideshowLeftArea: {
      position: 'absolute',
      left: 0,
      top: 100,
      bottom: 100,
      width: '30%',
      zIndex: 2,
    },
    slideshowRightArea: {
      position: 'absolute',
      right: 0,
      top: 100,
      bottom: 100,
      width: '30%',
      zIndex: 2,
    },
    slideshowIndicator: {
      position: 'absolute',
      bottom: screenOrientation === 'landscape' ? 30 : 60,
      backgroundColor: 'rgba(0,0,0,0.4)',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      zIndex: 3,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.1)',
    },
    slideshowIndicatorText: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 14,
      fontWeight: '600',
      fontVariant: ['tabular-nums'],
    },
    slideshowHint: {
      position: 'absolute',
      top: 100,
      alignSelf: 'center',
      backgroundColor: 'rgba(0,0,0,0.6)',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
      zIndex: 3,
    },
    slideshowHintText: {
      color: '#fff',
      fontSize: 14,
      textAlign: 'center',
    },
    // 時計・日付オーバーレイのスタイル
    clockOverlay: {
      position: 'absolute',
      bottom: screenOrientation === 'landscape' ? 30 : 80,
      left: 0,
      right: 0,
      backgroundColor: 'transparent',
      paddingHorizontal: 20,
      paddingVertical: 10,
      zIndex: 5,
      alignItems: 'center',
    },
    clockText: {
      color: '#fff',
      fontSize: (screenOrientation === 'landscape' ? 96 : 100) * (clockDateSize === 'small' ? 0.6 : clockDateSize === 'medium' ? 0.8 : 1.2),
      fontWeight: '200',
      letterSpacing: 2,
      fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', web: 'monospace' }),
      textShadowColor: 'rgba(0, 0, 0, 0.5)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    },
    dateText: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: (screenOrientation === 'landscape' ? 36 : 40) * (clockDateSize === 'small' ? 0.6 : clockDateSize === 'medium' ? 0.8 : 1.2),
      marginTop: 0,
      fontWeight: '300',
      textShadowColor: 'rgba(0, 0, 0, 0.5)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    },
    // 警告モーダルのスタイル (Modernized)
    warningOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    warningModal: {
      backgroundColor: '#2A2A2A',
      padding: 24,
      borderRadius: 20,
      maxWidth: 340,
      width: '100%',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.1)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 10,
    },
    warningTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 12,
      color: '#fff',
    },
    warningMessage: {
      fontSize: 16,
      lineHeight: 24,
      textAlign: 'center',
      marginBottom: 24,
      color: 'rgba(255,255,255,0.8)',
    },
    warningButton: {
      backgroundColor: '#007AFF',
      paddingVertical: 14,
      paddingHorizontal: 30,
      borderRadius: 12,
      width: '100%',
    },
    warningButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
    },
    // スライドショーエラー表示のスタイル
    slideshowErrorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 40,
    },
    slideshowErrorText: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: 18,
      textAlign: 'center',
      marginBottom: 20,
      marginTop: 20,
    },
    slideshowNextButton: {
      backgroundColor: 'rgba(255,255,255,0.1)',
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 25,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    slideshowNextButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    // 写真情報表示のスタイル
    photoInfo: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: 'rgba(0,0,0,0.6)',
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    photoInfoText: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 12,
      textAlign: 'center',
      fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },
  });
};
